version: "3.8"

services:
  frontend-dc-church:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-dc-church
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
